apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app: guestbook 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: us.icr.io/${YOUR_NAMESPACE}/guestbook
        imagePullPolicy: Always
        name: guestbook
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 50m
            memory: 512Mi
          requests:
            cpu: 20m
            memory: 256Mi
        env:
        - name: REDIS_MASTER_SERVICE_HOST
          value: "redis-master"
        - name: REDIS_MASTER_SERVICE_PORT
          value: "6379"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"